import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guideSidebar: [{type: 'autogenerated', dirName: '.'}],
  openApiSidebar: [
    {
      type: 'category',
      label: '开放平台说明',
      items: [
        'open-api/platform-guide/overview',
        'open-api/platform-guide/api-key',
      ],
    },
    {
      type: 'category',
      label: 'API详情',
      items: [
        'open-api/api-docs/overview',
        'open-api/api-docs/system',
        'open-api/api-docs/movie',
        'open-api/api-docs/translate',
        'open-api/api-docs/appendix',
      ],
    },
  ],
};

export default sidebars;
